[versions]
agp = "8.13.1"
connectClientVersion = "1.1.0"
datastorePreferences = "1.1.7"
kotlin = "2.2.21"
junit = "4.13.2"
kotlinxSerializationJson = "1.9.0"
amapLocation = "6.5.1"
mockk = "1.14.6"
okhttp = "5.3.1"
reorderable = "3.0.0"

[libraries]
androidx-connect-client = { module = "androidx.health.connect:connect-client", version.ref = "connectClientVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
amapLocation = { module = "com.amap.api:location", version.ref = "amapLocation" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.9.4" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.11.0" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.11.00" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
